MMotors/config/routes.rb
Rails.application.routes.draw do
  resources :dveiculos
  resources :veiculos
  devise_for :users
  get "veiculos/contato"
	root to: "veiculos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MMotors/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MMotors/app/models/dveiculo.rb
class Dveiculo < ApplicationRecord
	validates_presence_of :nome
    validates_presence_of :email
    validates_presence_of :telefone
    validates_presence_of :modelo
    validates_presence_of :info_adicional
    
end

MMotors/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

MMotors/app/models/veiculo.rb
class Veiculo < ApplicationRecord
	validates_presence_of :modelo
    validates_presence_of :marca
    validates_presence_of :preco
    validates_presence_of :cor
    validates_presence_of :combustivel
    validates_presence_of :transmissao
    validates_presence_of :potencia
    validates_presence_of :imagem

end

MMotors/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

MMotors/app/controllers/dveiculos_controller.rb
class DveiculosController < ApplicationController
  before_action :set_dveiculo, only: [:show, :edit, :update, :destroy]


  # GET /dveiculos
  # GET /dveiculos.json
  def index
    @dveiculos = Dveiculo.all
  end

  # GET /dveiculos/1
  # GET /dveiculos/1.json
  def show
  end

  # GET /dveiculos/new
  def new
    @dveiculo = Dveiculo.new
  end

  # GET /dveiculos/1/edit
  def edit
  end

  # POST /dveiculos
  # POST /dveiculos.json
  def create
    @dveiculo = Dveiculo.new(dveiculo_params)

    respond_to do |format|
      if @dveiculo.save
        format.html { redirect_to @dveiculo, notice: 'Dveiculo was successfully created.' }
        format.json { render :show, status: :created, location: @dveiculo }
      else
        format.html { render :new }
        format.json { render json: @dveiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dveiculos/1
  # PATCH/PUT /dveiculos/1.json
  def update
    respond_to do |format|
      if @dveiculo.update(dveiculo_params)
        format.html { redirect_to @dveiculo, notice: 'Dveiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @dveiculo }
      else
        format.html { render :edit }
        format.json { render json: @dveiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dveiculos/1
  # DELETE /dveiculos/1.json
  def destroy
    @dveiculo.destroy
    respond_to do |format|
      format.html { redirect_to dveiculos_url, notice: 'Dveiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dveiculo
      @dveiculo = Dveiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dveiculo_params
      params.require(:dveiculo).permit(:modelo, :marca, :cor, :freio, :painel, :info_adicional, :nome, :telefone ,:email )
    end
end

MMotors/app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :update, :edit, :destroy]
  # GET /veiculos
  # GET /veiculos.json
  def index
    @veiculos = Veiculo.all
  end
  def catalogo
    @veiculos = Veiculo.all
  end
  
  # GET /veiculos/1
  # GET /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos
  # POST /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully created.' }
        format.json { render :show, status: :created, location: @veiculo }
      else
        format.html { render :new }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1
  # PATCH/PUT /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @veiculo }
      else
        format.html { render :edit }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1
  # DELETE /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: 'Veiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veiculo_params
      params.require(:veiculo).permit(:modelo, :marca, :cor, :preco, :combustivel, :transmissao, :potencia, :informacao_adicional, :imagem)
    end
end

MMotors/app/helpers/application_helper.rb
module ApplicationHelper
end

MMotors/app/helpers/dveiculos_helper.rb
module DveiculosHelper
end

MMotors/app/helpers/eveiculos_helper.rb
module EveiculosHelper
end

MMotors/app/helpers/home_helper.rb
module HomeHelper
end

MMotors/app/helpers/pedidos_helper.rb
module PedidosHelper
end

MMotors/app/helpers/veiculos_helper.rb
module VeiculosHelper
end

MMotors/app/views/dveiculos/_form.html.erb
<%= form_with(model: dveiculo, local: true) do |form| %>
  <% if dveiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dveiculo.errors.count, "error") %> prohibited this dveiculo from being saved:</h2>

      <ul>
      <% dveiculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h2>Sobre você</h2>
  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>
<div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone%>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
   <h2>Veiculo</h2>
  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo %>
  </div>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca %>
  </div>

  <div class="field">
    <%= form.label :cor %>
    <%= form.text_field :cor %>
  </div>

  <div class="field">
    <%= form.label :freio %>
    <%= form.text_field :freio %>
  </div>

  <div class="field">
    <%= form.label :painel %>
    <%= form.text_field :painel %>
  </div>

  <div class="field">
    <%= form.label :info_adicional %>
    <%= form.text_area :info_adicional %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

MMotors/app/views/dveiculos/edit.html.erb
<h1>Editing Dveiculo</h1>

<%= render 'form', dveiculo: @dveiculo %>

<%= link_to 'Show', @dveiculo %> |
<%= link_to 'Back', dveiculos_path %>

MMotors/app/views/dveiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Veiculos para avaliar</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Marca</th>
      <th>Cor</th>
      <th>Freio</th>
      <th>Painel</th>
      <th>Info adicional</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dveiculos.each do |dveiculo| %>
      <tr>
        <td><%= dveiculo.modelo %></td>
        <td><%= dveiculo.marca %></td>
        <td><%= dveiculo.cor %></td>
        <td><%= dveiculo.freio %></td>
        <td><%= dveiculo.painel %></td>
        <td><%= dveiculo.info_adicional %></td>
        <td><%= link_to 'Show', dveiculo %></td>
        <%if !user_signed_in? %>
        <td><%= link_to 'Edit', edit_dveiculo_path(dveiculo) %></td>
        <%= link_to 'New Dveiculo', new_dveiculo_path %>
        <%end%>
        <td><%= link_to 'Destroy', dveiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

MMotors/app/views/dveiculos/new.html.erb
<div class =mu-clients-area>
<h1>Veiculo personalizado</h1>

<%= render 'form', dveiculo: @dveiculo %>

<h2><%= link_to 'Back', root_path %></h2>
</div>

MMotors/app/views/dveiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @dveiculo.modelo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @dveiculo.marca %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @dveiculo.cor %>
</p>

<p>
  <strong>Freio:</strong>
  <%= @dveiculo.freio %>
</p>

<p>
  <strong>Painel:</strong>
  <%= @dveiculo.painel %>
</p>

<p>
  <strong>Info adicional:</strong>
  <%= @dveiculo.info_adicional %>
</p>

<%= link_to 'Edit', edit_dveiculo_path(@dveiculo) %> |
<%= link_to 'Back', dveiculos_path %>

MMotors/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <title>MMotors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', 'bootstrap.min', 'font-awesome.min', 'slick', 'style' %>
    <%= javascript_include_tag 'application', 'bootstrap.min', 'cable', 'custom', 'app', 'slick.min'%>
    <%= stylesheet_link_tag  'theme-color/default-theme', id: "switcher" %>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>MMotors</title>
      <!-- Favicon -->
      <link rel="shortcut icon" type="image/icon" href="assets/images/favicon.ico"/>
      <!-- Font Awesome -->
      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
       <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      <!-- Slick slider -->
      <!-- Theme color -->
      
      <!-- Poppins For Title -->
       <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
   
  </head>

  <body>
   <!--START SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#">
      <i class="fa fa-angle-up"></i>
    </a>
  <!-- END SCROLL TOP BUTTON -->
    
    <!-- Start Header -->
  <header id="mu-hero">
    <div class="container">
      <div class="mu-hero-area">
        
        <div class="mu-hero-top">
          <!-- Start center Logo -->
          <div class="mu-logo-area">
            <!-- text based logo -->
            <a class="mu-logo" href=<%=root_path%>><span>MMotors</span></a>
            <!-- Image based logo -->
            <!-- <a class="mu-logo" href="index.html"><img src="assets/images/logo.jpg" alt="logo img"></a> -->
          </div>

          <div class="area-admin">
            <!-- text based logo -->
            <% if !user_signed_in? %>
            <a class="btn btn-default" href=<%= new_user_session_path %>>Login</a>
            <%end%>
            <%if user_signed_in? %>
            <a class="btn btn-default" data-method="delete" href=<%=destroy_user_session_path%>>logout</a>
            <%end%>
      
          </div>

          <!-- End center Logo -->
          
        </div>
      </div>
    </div>
  </header>
  <!-- End Header -->
        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  
  <div>
  <div class =mu-clients-area>
    <%= yield %>
    </div>
  </div> 

  <footer id="mu-footer">
    <div class="container">
      <div class="mu-footer-area">
        <div class="row">
          <div class="col-md-6">
            <div class="mu-footer-left">
              <p class="mu-copy-right">&copy; Copyright MMotors. All right reserved.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

  </footer>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script> 
  </body>  
</html>

MMotors/app/views/veiculos/_form.html.erb
<div class =mu-clients-area>
<%= form_with(model: veiculo, local: true) do |form| %>
  <% if veiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(veiculo.errors.count, "error") %> prohibited this veiculo from being saved:</h2>

      <ul>
      <% veiculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo %>
  </div>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca %>
  </div>

  <div class="field">
    <%= form.label :cor %>
    <%= form.text_field :cor %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :combustivel %>
    <%= form.text_field :combustivel %>
  </div>

  <div class="field">
    <%= form.label :transmissao %>
    <%= form.text_field :transmissao %>
  </div>

  <div class="field">
    <%= form.label :potencia %>
    <%= form.text_field :potencia %>
  </div>

  <div class="field">
    <%= form.label :informacao_adicional %>
    <%= form.text_area :informacao_adicional %>
  </div>

  <div class="field">
    <%= form.label :Imagem  %>
    <%= form.text_area :imagem%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

MMotors/app/views/veiculos/contato.html.erb
<h1>Contate-nos</h1>
<h2>telefone</h2>
<h3> 4002-8933</h3>
<h2>Email</h2>
<h3> MMotors@gmail.com</h3>

MMotors/app/views/veiculos/edit.html.erb
<h1>Editing Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>

<h3><%= link_to 'Show', @veiculo %> |
<%= link_to 'Back', veiculos_path %></h3>

MMotors/app/views/veiculos/index.html.erb
<p id="notice"><%= notice %></p>

<div>
<br>
 <%if user_signed_in? %>
  <h2><%= link_to 'Adiconar veiculo', new_veiculo_path %></h2>
  <h2><%= link_to 'pedidos', dveiculos_path %></h2>

      
 <% end%>
      <!-- Start Featured Tours -->
    <section id="mu-featured-tours">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="mu-featured-tours-area">
              <h2>MMmotors</h2>
              <p class="mu-title-content">Site que você encontrará os melhores veículos, com preços que cabem no bolso! </p>
              <br>

              <!-- Start Featured Tours content -->
              <div class="mu-featured-tours-content">
                <div class="row">
                <% @veiculos.each do |veiculo| %>
                  <div class="col-md-4">
                    <div class="mu-featured-tours-single">

                      <img class="img-square" src="<%= veiculo.imagem%>" alt="img" width="350" height="350">
                      <div class="mu-featured-tours-single-info">
                        <h3><%=veiculo.modelo%></h3>
                       <br>
                       <h3>R$<%=veiculo.preco%></h3>
                       <h2><%= link_to 'Ver', veiculo %></h2>
                       <%if user_signed_in? %>
                          <h2><%= link_to 'Editar', edit_veiculo_path(veiculo) %></h2>
                             <h2><%= link_to 'Destruir', veiculo, method: :delete, data: { confirm: 'Are you sure?' } %></h2>

      
                        <% end%>
                      </div>
                    </div>

        
                  </div>
                <%end%>  

                  

                </div>
              </div>
              <!-- End Featured Tours content -->
              <!-- Start Call to Action -->
          <section id="mu-callto-action">
            <div class="container">
              <div class="row col-md-12">
                <div class="mu-callto-action-area">
                  <h2>Descreva o veiculo que entramos em contato</h2>
                  <h2><%= link_to 'Descrever', new_dveiculo_path %></h2>
                </div>
              </div>
            </div>
          </section>
          <!-- Start Call to Action -->
            </div>
          </div>
        </div>
      </div>
    </section>

</div>

MMotors/app/views/veiculos/new.html.erb
<div class =mu-clients-area>
<h1>Novo veiculo</h1>


<%= render 'form', veiculo: @veiculo %>

<h3><%= link_to 'Back', veiculos_path %></h3>
</div>

MMotors/app/views/veiculos/show.html.erb
<p id="notice"><%= notice %></p>
<div class =mu-clients-area>
  <p>
   <img class="img-square" src="<%= @veiculo.imagem%>" alt="img" width="350" height="350">
  </p>
  <p>
    <strong>Modelo:</strong>
    <%= @veiculo.modelo %>
  </p>

  <p>
    <strong>Marca:</strong>
    <%= @veiculo.marca %>
  </p>

  <p>
    <strong>Cor:</strong>
    <%= @veiculo.cor %>
  </p>

  <p>
    <strong>Preco:</strong>
    <%= @veiculo.preco %>
  </p>

  <p>
    <strong>Combustivel:</strong>
    <%= @veiculo.combustivel %>
  </p>

  <p>
    <strong>Transmissao:</strong>
    <%= @veiculo.transmissao %>
  </p>

  <p>
    <strong>Potencia:</strong>
    <%= @veiculo.potencia %>
  </p>
  
  <p>
    <strong>Informacao adicional:</strong>
    <%= @veiculo.informacao_adicional %>
  </p>

   <%if user_signed_in? %>
    <%= link_to 'Edit', edit_veiculo_path(@veiculo) %> 
      
    <% end%>

 <br>
 <h2>Contate-nos</h2>
  <h2>telefone</h2>
<h3> 4002-8933</h3>
<h2>Email</h2>
<h3> MMotors@gmail.com</h3>
</br>
<%= link_to 'Back', veiculos_path %>

</div>